services:
  db:
    image: postgres:16
    container_name: hr_bot_db
    environment:
      POSTGRES_DB: hr_bot_db
      POSTGRES_USER: hr_bot_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: hr_bot_web

    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  postgres_data:

